### ISSUE TITLE
The Website can't be accessed

### ISSUE THREAD

**Issue by cdreama8** [Dynatrace/mobile-hotday-2018#1]
Dynatrace https://cnz35449.sprint.dynatracelabs.com
Username u3879401@mvrht.net
Password MobileHOT2018
But I can't log in with the Username and Password.

easyTravel UI http://ec2-35-168-8-170.compute-1.amazonaws.com:8079
Username maria
Password maria

The easyTravel UI cannot be accessed.

**Comment by dominikp** [comment]
The environment is no longer available. It was set up for the Perform Training session in January 2018 and kept running for a month. You can still go through the lessons but you'll need to use your own environment.
